name: Build, publish and deploy to MonsterASP.NET
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Publish
        uses: ./.github/actions/build-publish-folder
        with:
          dotnet-version: '9.0'
          configuration: 'Release'
          runtime: 'win-x86'
          output-path: './publish'

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
